name: harmony-concat
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - jupyter
  - xarray
  - netCDF4
  - matplotlib
  - basemap
  - nb_conda_kernels
  - cartopy
  - pip
  - pip:
    - harmony-py>=0.4
