name: swotea
channels:
  - conda-forge
  - defaults
dependencies:
  - cartopy=0.18.0
  - dask=2021.2.0
  - ffmpeg=4.3.1
  - folium=0.12.0
  - matplotlib=3.3.4
  - netcdf4=1.5.6
  - notebook=6.2.0
  - numpy=1.20.0
  - pandas=1.2.3
  - requests=2.25.1
  - s3fs=0.5.2
  - xarray=0.17.0
  - zarr=2.6.1